package storage

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/robert-nemet/sessionmngr/internal/config"
	"github.com/robert-nemet/sessionmngr/internal/session"
	"github.com/robert-nemet/sessionmngr/internal/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSaveSession(t *testing.T) {
	tmpDir := t.TempDir()
	testutil.SetEnvForTest(t, config.EnvStorageLocation, tmpDir)
	cfg := config.NewConfig()

	now := time.Now()

	// Create session without UUID (storage will generate it)
	sess := &session.Session{
		UUID:          "",
		Title:         "Test Session",
		CreatedAt:     now,
		LastUpdatedAt: now,
		Tags:          []string{"test"},
		Messages: []session.Message{
			{Role: "user", Content: "Test question"},
			{Role: "assistant", Content: "Test answer"},
		},
	}

	store := NewBasicStorage(cfg)
	savedSess, err := store.SaveSession(context.Background(), sess)
	require.NoError(t, err)

	uuid := savedSess.UUID
	require.NotEmpty(t, uuid, "UUID should be generated by storage")

	// Verify raw.json was created
	filePath := filepath.Join(tmpDir, uuid, "raw.json")
	data, err := os.ReadFile(filePath)
	require.NoError(t, err, "Failed to read raw.json")

	var loaded session.Session
	require.NoError(t, json.Unmarshal(data, &loaded))

	assert.Equal(t, uuid, loaded.UUID)
	assert.Equal(t, "Test Session", loaded.Title)
	assert.Len(t, loaded.Messages, 2)

	// Verify index.json was created
	indexPath := filepath.Join(tmpDir, "index.json")
	indexData, err := os.ReadFile(indexPath)
	require.NoError(t, err, "Failed to read index.json")

	var idx SessionIndex
	require.NoError(t, json.Unmarshal(indexData, &idx))

	require.Len(t, idx.Sessions, 1)
	assert.Equal(t, uuid, idx.Sessions[0].UUID)
}

func TestLoadSession(t *testing.T) {
	tmpDir := t.TempDir()
	testutil.SetEnvForTest(t, config.EnvStorageLocation, tmpDir)
	cfg := config.NewConfig()

	uuid := "test-load-uuid"
	now := time.Now()

	// Save a session first
	sess := &session.Session{
		UUID:          uuid,
		Title:         "Load Test",
		CreatedAt:     now,
		LastUpdatedAt: now,
		Tags:          []string{},
		Messages: []session.Message{
			{Role: "user", Content: "Question"},
		},
	}

	store := NewBasicStorage(cfg)
	_, err := store.SaveSession(context.Background(), sess)
	require.NoError(t, err)

	// Load it back
	loaded, err := store.LoadSession(context.Background(), uuid)
	require.NoError(t, err)

	assert.Equal(t, uuid, loaded.UUID)
	assert.Equal(t, "Load Test", loaded.Title)
	assert.Len(t, loaded.Messages, 1)
}

func TestFindSessionByPrefix(t *testing.T) {
	tmpDir := t.TempDir()
	testutil.SetEnvForTest(t, config.EnvStorageLocation, tmpDir)
	cfg := config.NewConfig()

	store := NewBasicStorage(cfg)

	// Create a session
	uuid := "550e8400-e29b-41d4-a716-446655440000"
	sess := &session.Session{
		UUID:          uuid,
		Title:         "Prefix Test",
		CreatedAt:     time.Now(),
		LastUpdatedAt: time.Now(),
		Tags:          []string{},
		Messages:      []session.Message{},
	}

	_, err := store.SaveSession(context.Background(), sess)
	require.NoError(t, err)

	// Test finding by 8-char prefix
	found, err := store.FindSessionByPrefix(context.Background(), "550e8400")
	require.NoError(t, err)
	assert.Equal(t, uuid, found.UUID)

	// Test prefix too short
	_, err = store.FindSessionByPrefix(context.Background(), "550e8")
	assert.Error(t, err, "Expected error for prefix too short")

	// Test not found
	_, err = store.FindSessionByPrefix(context.Background(), "deadbeef")
	assert.Error(t, err, "Expected error for not found")
}

func TestListSessions(t *testing.T) {
	tmpDir := t.TempDir()
	testutil.SetEnvForTest(t, config.EnvStorageLocation, tmpDir)
	cfg := config.NewConfig()

	store := NewBasicStorage(cfg)

	// Create multiple sessions with different timestamps
	for i := range 14 {
		sess := &session.Session{
			UUID:          generateTestUUID(i),
			Title:         "Session " + string(rune('A'+i)),
			CreatedAt:     time.Now().Add(time.Duration(-i) * time.Hour),
			LastUpdatedAt: time.Now().Add(time.Duration(-i) * time.Hour),
			Tags:          []string{},
			Messages:      []session.Message{},
		}
		_, err := store.SaveSession(context.Background(), sess)
		require.NoError(t, err)
	}

	// Test pagination - page 1
	sessions, totalPages, totalSessions, err := store.ListSessions(context.Background(), 1, 10, nil)
	require.NoError(t, err)

	assert.Len(t, sessions, 10)
	assert.Equal(t, 2, totalPages)
	assert.Equal(t, 14, totalSessions)

	// Verify sorting (most recent first)
	assert.Equal(t, "Session A", sessions[0].Title)

	// Test page 2 (should have remaining 4 sessions from 14 total)
	sessions2, _, totalSessions2, err := store.ListSessions(context.Background(), 2, 10, nil)
	require.NoError(t, err)

	assert.Equal(t, 14, totalSessions2)
	assert.Len(t, sessions2, 4)
}

func TestUpdateTags(t *testing.T) {
	tmpDir := t.TempDir()
	testutil.SetEnvForTest(t, config.EnvStorageLocation, tmpDir)
	cfg := config.NewConfig()

	store := NewBasicStorage(cfg)
	ctx := context.Background()

	// Create a session with messages and initial tags
	now := time.Now()
	sess := &session.Session{
		Title:         "Tag Test",
		CreatedAt:     now,
		LastUpdatedAt: now,
		Tags:          []string{"initial"},
		Messages: []session.Message{
			{Role: "user", Content: "hello"},
			{Role: "assistant", Content: "hi"},
		},
	}
	saved, err := store.SaveSession(ctx, sess)
	require.NoError(t, err)

	// Update tags
	err = store.UpdateTags(ctx, saved.UUID, []string{"initial", "new-tag", "another"})
	require.NoError(t, err)

	// Reload and verify tags updated
	loaded, err := store.LoadSession(ctx, saved.UUID)
	require.NoError(t, err)
	assert.Equal(t, []string{"initial", "new-tag", "another"}, loaded.Tags)

	// Verify messages were NOT modified
	assert.Len(t, loaded.Messages, 2)
	assert.Equal(t, "hello", loaded.Messages[0].Content)

	// Verify index also updated
	sessions, _, _, err := store.ListSessions(ctx, 1, 10, []string{"new-tag"})
	require.NoError(t, err)
	assert.Len(t, sessions, 1)
	assert.Equal(t, "Tag Test", sessions[0].Title)
}

func TestUpdateTagsNotFound(t *testing.T) {
	tmpDir := t.TempDir()
	testutil.SetEnvForTest(t, config.EnvStorageLocation, tmpDir)
	cfg := config.NewConfig()

	store := NewBasicStorage(cfg)
	ctx := context.Background()

	err := store.UpdateTags(ctx, "nonexistent-uuid-1234", []string{"tag"})
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "session not found")
}

func generateTestUUID(i int) string {
	// Generate unique UUIDs for testing
	base := "550e8400-e29b-41d4-a716-"
	suffix := ""
	for len(suffix) < 12 {
		suffix = suffix + string(rune('0'+i%10))
		i = i / 10
	}
	return base + suffix
}
