// Package storage provides interfaces and implementations for persisting session data.
// Design decisions tracked here:
// - UUID generation moved to storage layer (not session factory) to enable title-based deduplication
// - Index operations (loadIndex, saveIndex, addToIndex) are private implementation details, not in interface
// - SaveSession returns (*Session, error) to support "get or create" semantics for title uniqueness
// - Context is threaded through all operations for cancellation and timeout support (especially Postgres)
package storage

import (
	"context"
	"time"

	"github.com/robert-nemet/sessionmngr/internal/session"
)

// Summary represents a single AI-generated summary of a conversation or portion thereof.
// ID is a UUID generated by the storage layer.
// Summaries are stored in {session_uuid}/summaries/{summary_uuid}.json
type Summary struct {
	ID           string       `json:"id"` // UUID generated by storage
	SessionID    string       `json:"session_id"`
	Model        string       `json:"model"`         // AI model used
	PromptSource string       `json:"prompt_source"` // "default" or file path
	CreatedAt    time.Time    `json:"created_at"`
	MessageRange MessageRange `json:"message_range"`
	Content      Content      `json:"content"`
}

// MessageRange specifies which messages were summarized.
type MessageRange struct {
	Start int `json:"start"`
	End   int `json:"end"`
}

// Content contains the AI-generated summary.
type Content struct {
	Title    string `json:"title"`    // Short title for listing
	Markdown string `json:"markdown"` // Full summary as markdown
}

// Storage defines the interface for session persistence operations.
// Implementations must handle:
// - Title-based deduplication (SaveSession returns existing session if title matches)
// - UUID generation for new sessions
// - Atomic writes to both session files and index
// All methods accept context for cancellation and timeout support.
type Storage interface {
	// FindSessionByTitle returns a session with matching title, or error if not found.
	FindSessionByTitle(ctx context.Context, title string) (*session.Session, error)

	// SaveSession persists a session to storage.
	// If sess.UUID is empty, creates new session with generated UUID.
	// If sess.UUID is empty and title exists, returns existing session (deduplication).
	// If sess.UUID is set, updates existing session.
	// Returns the saved or existing session with UUID populated.
	SaveSession(ctx context.Context, sess *session.Session) (*session.Session, error)

	// LoadSession retrieves a session by full UUID.
	// Returns error if session does not exist.
	LoadSession(ctx context.Context, uuid string) (*session.Session, error)

	// FindSessionByPrefix finds a session by UUID prefix (minimum 8 characters).
	// Returns error if prefix matches zero or multiple sessions.
	// Returns error if prefix is less than 8 characters.
	FindSessionByPrefix(ctx context.Context, prefix string) (*session.Session, error)

	// SessionExists checks if a session with given UUID exists.
	SessionExists(ctx context.Context, uuid string) bool

	// DeleteSession removes a session and all its summaries from storage.
	// Returns error if session does not exist.
	DeleteSession(ctx context.Context, uuid string) error

	// ListSessions returns paginated session summaries sorted by LastUpdatedAt descending.
	// Returns (summaries, totalPages, totalSessions, error).
	// Page numbers start at 1.
	// If tags is non-empty, only sessions matching any of the given tags are returned.
	ListSessions(ctx context.Context, page int, perPage int, tags []string) ([]SessionSummary, int, int, error)

	// SaveSummary persists a summary to storage.
	// Generates a UUID for summary.ID if not set (storage owns ID generation).
	// If summary.ID is provided, validates it's a valid UUID format.
	// Creates {uuid}/summaries/ directory if needed.
	// Validates that summary.CreatedAt and summary.Content.Title are set.
	// Generates filename: {summary_uuid}.json
	// Updates metadata.json with summary entry.
	// If summary.ID already exists, overwrites the existing summary file.
	// Returns error if validation fails or session does not exist.
	SaveSummary(ctx context.Context, sessionID string, sum *Summary) error

	// ListSummaries returns metadata for all summaries in a session.
	// Returns SummaryEntry (not full Summary) for memory efficiency.
	// Returns empty slice if no summaries exist (not an error).
	ListSummaries(ctx context.Context, sessionID string) ([]SummaryEntry, error)

	// LoadAllSummaries retrieves all summaries for a session in a single operation.
	// Returns full Summary objects including Content.
	// More efficient than calling LoadSummary in a loop (avoids N+1 queries).
	// Returns empty slice if no summaries exist (not an error).
	LoadAllSummaries(ctx context.Context, sessionID string) ([]Summary, error)

	// LoadSummary retrieves a specific summary by session ID and summary ID.
	// Returns the full Summary including Content.
	// Returns error if summary does not exist.
	LoadSummary(ctx context.Context, sessionID, summaryID string) (*Summary, error)

	// DeleteSummary removes a summary from storage.
	// Deletes the summary file and removes entry from metadata.
	// Returns error if session or summary does not exist.
	DeleteSummary(ctx context.Context, sessionID, summaryID string) error

	// ValidateAPIKey checks if an API key hash is valid for a given user ID.
	// Returns true if the key exists, belongs to the user, and is active.
	// Updates last_used_at timestamp asynchronously if valid.
	ValidateAPIKey(ctx context.Context, keyHash, userID string) (bool, error)

	// CountSummariesToday returns the number of summaries created today by the current user.
	// Returns 0 if no summaries have been created today.
	CountSummariesToday(ctx context.Context) (int, error)

	// TrackSummary increments the daily summary count for the current user.
	TrackSummary(ctx context.Context) error

	// UpdateTags replaces the tags on a session without touching other fields.
	UpdateTags(ctx context.Context, sessionID string, tags []string) error
}

// SessionIndex represents the index.json file structure.
// This file enables fast session discovery without loading full session data.
type SessionIndex struct {
	Sessions []SessionSummary `json:"sessions"`
}

// SessionSummary is lightweight metadata for listing sessions.
// Contains only essential information without full message history.
type SessionSummary struct {
	UUID          string    `json:"uuid"`
	Title         string    `json:"title"`
	MessageCount  int       `json:"message_count"`
	SummaryCount  int       `json:"summary_count"`
	Tags          []string  `json:"tags,omitempty"`
	LastUpdatedAt time.Time `json:"last_updated_at"`
}

// SummaryMetadata tracks all summaries for a session.
// Stored in {uuid}/summaries/metadata.json
type SummaryMetadata struct {
	SessionID string         `json:"session_id"`
	Summaries []SummaryEntry `json:"summaries"`
}

// SummaryEntry is metadata about a single summary.
// Used both in metadata.json and as return type for ListSummaries.
type SummaryEntry struct {
	ID           string       `json:"id"`
	SessionID    string       `json:"session_id"`
	Title        string       `json:"title"`
	Model        string       `json:"model"`
	MessageRange MessageRange `json:"message_range"`
	CreatedAt    time.Time    `json:"created_at"`
}

// summaryFilename returns the filename for a summary given its ID.
func summaryFilename(summaryID string) string {
	return summaryID + ".json"
}
