package session

import (
	"fmt"
	"time"
)

// NewSession creates a new Session instance with the given title.
// If title is empty, generates a default title with current timestamp.
// The UUID field is left empty and will be generated by the storage layer.
// Design decision: UUID generation is responsibility of storage to enable title-based deduplication.
func NewSession(title string) *Session {
	now := time.Now()

	if title == "" {
		title = fmt.Sprintf("New conversation %s", now.Format("2006-01-02 15:04"))
	}

	return &Session{
		UUID:          "", // UUID will be generated by storage layer
		Title:         title,
		Messages:      make([]Message, 0),
		CreatedAt:     now,
		LastUpdatedAt: now,
		Tags:          make([]string, 0),
	}
}
